BloggerBlogBundle_homepage:
    path:     /
    defaults: { _controller: "BloggerBlogBundle:Page:index" }
    requirements:
         methods:  GET
         
BloggerBlogBundle_about:
    path:   /about
    defaults: { _controller: "BloggerBlogBundle:Page:about" }
    requirements:
         methods:  GET

BloggerBlogBundle_blog_show:
    path:  /{id}
    defaults: { _controller: "BloggerBlogBundle:Blog:show" }
    requirements:
        methods:  GET
        id: \d+

BloggerBlogBundle_shoes:
    path:   /shoes
    defaults: { _controller: "BloggerBlogBundle:Page:shoes" }
    requirements:
         methods:  GET

BloggerBlogBundle_invest:
    path:   /invest
    defaults: { _controller: "BloggerBlogBundle:Page:invest" }
    requirements:
         methods:  GET
